const CHANNELS = {
  'UCIvQJmPaDR2lMDDNhb4--bA': 'Quatro-Rodas',
  'UCWYuQ9_2boHBxm59n6lSzDA': 'Autoesporte', 
  'UC6Rk7BKVPWkFJ9FiBrts5Vg': 'motor1brasil',
  'UCGhErKQ6LBiCsXE8fWtokfg': 'automaisoficial',
  'UCz2Bb7YdduN4x7qN9oFrJjQ': 'webmotors',
  'UCGBIIPnw0AYM3BFsmTsjeAw': 'Acelerados',
  'UCM7Ysb5r_tVbxGabjTSQgkA': 'decaronacomleandro',
  'UCqtPuAH8q5CgZyp8hklSpNA': 'Macchina',
  'UCoenHRLtKKtutvOQGZzqpCQ': 'duasrodasbr',
  'UC--87koyZy53LgIEBCA1qgg': 'motociclismoonline',
  'UCfReg1ecXWG9Gscjba-dGgw': 'FullpowerTV',
  'UC88Hb8Q8ffGONG7h_W1WXZA': 'UltimaMarcha',
  'UCi7NjYyIQk6hPRbZ4BVKHyw': 'FlatOutBrasil',
  'UCdvtAyfO0ZVfA-UV-lssMQw': 'CanalMotoPlay',
  'UCeLSGU99FGfp77C9WqT15lw': 'Vansfaria',
  'UCJ8A6N9UFaf04Uxf6rLXmPA': 'OntheRoadBr',
  'UCrzsIJIQN_OZPqCa4S7N0rw': 'Pilotoleandromello',
  'UCt_oS5q8BA5iiXv_mmqSByQ': 'PARodaTV',
  'UCMk1wBIsHmalYeE16GkD6bg': 'CarroChefe',
  'UCRQxRSO8SSm6aQV19fjy7UQ': 'CassioCortes',
  'UCIE4i9-elbrBWAtKyJrNdLA': 'durvalcareca',
  'UCNScJ8tFmWbP1QjcKwScK5w': 'MinutoMotor',
  'UCdQiJIRylGydCsHQtCUsTJg': 'EstadaoMobilidade',
  'UChUvS75BR7ziAr7WhrecVsA': 'AutoPapo',
  'UCCykAaNbtxUpGwvkSYWWSKg': 'garagemdobelloteTV',
  'UCPmRf82yxqPJkmfnFzm9Wlw': 'KS1951',
  'UCfyWVInB4nPkZGgiVwGtAiw': 'FalandoDeCarro',
  'UC-qF9N7a3k8v0F9XkSqasKw': 'Autorranking',
  'UCCbD39MVnMsTLGxsHLnOKlg': 'OutopInfinit0_',
  'UCx8Ako_xnMCOd3gDaCl5t7g': 'RevistaMotoAdventureOficial'
};

module.exports = { CHANNELS };